name: Tests and push apps

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  config:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@master
    
    - name: Setup node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: install

    - name: Check code formatting
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: prettier --check

    - name: Check code linting
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: lint

    - name: Check code typing
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: typecheck

    - name: Run unit tests
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: test --coverage

    - name: Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        files: ./coverage1.xml,./coverage2.xml # optional
        flags: unittests # optional
        name: codecov-umbrella # optional
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: phntxx/phntxx:latest